version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: cd backend && npm install
      - run:
          name: test
          command: cd backend && npm run test